name: ExamplePlugin
version: '${version}'
main: top.mrxiaom.example.ExamplePlugin
api-version: 1.16
depend: [ Vault ]
softdepend: [ PlaceholderAPI ]
authors: [ MrXiaoM ]
commands:
  example:
    description: awa
